---
api_key_users:
  -
    username: "test_key_user"
    first_name: "Test"
    last_name: "Key User"
    role: "API_KEY"
    api_key: "test-key"

external_auth_url: 'https://login-server.example.com'

datasource_api_keys:
  scopus: '1122334455'
