---
api_key_users:
  -
    username: "test_key_admin"
    first_name: "Test"
    last_name: "Key Admin"
    role: "API_KEY"
    api_key: "test-key"
  -
    username: "test_key_user"
    first_name: "Test"
    last_name: "Key User"
    role: "API_USER"
    api_key: "user-key"
  -
    username: "xtest"
    first_name: "Test"
    last_name: "Key User"
    role: "API_USER"
    api_key: "xtest-user-key"

external_auth_url: 'https://login-server.example.com'
journal_index_url: 'https://solr.example.com/journals/'

person_index_url:  'http://localhost:8983/solr/test-people/'

file_upload_root_dir: '/path/to/root/dir'

datasource_api_keys:
  scopus: '1122334455'

mail_settings:
  delivery_options:
    address: 'smtp.test.com'
    port: 25
  from_email: 'noreply@test.com'
  to_email: 'test@test.se'

override_file: '/tmp/test_gup_auth_override.enable'
