---
### USER ROLES DEFINITION
### Create a new role by adding another hash with a unique name of the role as well as a list of rights. Unassignable states that the role cannot be assigned to users.
### Available rights are: 'user', 'bibreview', 'delete_published'
roles:
  -
    name: ADMIN
    rights:
      - user
      - bibreview
      - delete_published
  -
    name: USER
    rights:
      - user
  -
    name: API_KEY
    rights:
      - user
      - bibreview
      - delete_published
    type: api
    unassignable: true
  -
    name: API_USER
    rights:
      - user
    type: api
    unassignable: true
