--- 
publication_form_templates: 
  article: 
    fields: 
      - 
        name: sourcetitle
        rule: R
      - 
        name: sourcevolume
        rule: O
      - 
        name: sourceissue
        rule: O
      - 
        name: sourcepages
        rule: O
      - 
        name: issn
        rule: O
      - 
        name: eissn
        rule: O
      - 
        name: article_number
        rule: O
  common: 
    fields: 
      - 
        name: title
        rule: R
      - 
        name: alt_title
        rule: O
      - 
        name: abstract
        rule: O
      - 
        name: pubyear
        rule: R
      - 
        name: publanguage
        rule: R
      - 
        name: category_hsv_local
        rule: R
      - 
        name: url
        rule: O
      - 
        name: extid
        rule: O
      - 
        name: links
        rule: O
      - 
        name: keywords
        rule: O
      - 
        name: keywords
        rule: O
      - 
        name: project
        rule: O
      - 
        name: pub_notes
        rule: O
      - 
        name: authors
        rule: R
  dissertation: 
    fields: 
      - 
        name: dissdate
        rule: O
      - 
        name: disstime
        rule: O
      - 
        name: disslocation
        rule: O
      - 
        name: dissopponent
        rule: O
      -
        name: issn
        rule: na
      -
        name: eissn
        rule: na
  monograph: 
    fields: 
      - 
        name: issn
        rule: O
      - 
        name: eissn
        rule: O
      - 
        name: extent
        rule: O
      - 
        name: publisher
        rule: O
      - 
        name: place
        rule: O
      - 
        name: series
        rule: O
      - 
        name: isbn
        rule: O
publication_types: 
  - 
    code: journal-articles
    content_types: 
      - ref
    form_templates: 
      - common
      - article
  - 
    code: review-articles
    content_types: 
      - ref
    form_templates: 
      - common
      - article
  - 
    code: editorial-letters
    content_types: 
      - vet
    form_templates: 
      - common
      - article
  - 
    code: book-reviews
    content_types: ~
    form_templates: 
      - common
      - article
  - 
    code: magazine-articles
    content_types: 
      - vet
      - pop
    form_templates: 
      - common
      - article
  - 
    code: books
    content_types: 
      - ref
      - vet
      - pop
    form_templates: 
      - common
      - monograph
  - 
    code: book-chapters
    content_types: 
      - ref
      - vet
      - pop
    fields: 
      - 
        name: sourcetitle
        rule: R
    form_templates: 
      - common
      - monograph
  - 
    code: translations
    content_types: 
      - vet
    fields: 
      - 
        name: authors
        rule: na
      - 
        name: editor
        rule: R
    form_templates: 
      - common
      - monograph
  -
    code: doctoral-thesis
    content_types:
      - vet
    form_templates:
      - common
      - monograph
      - dissertation
  - 
    code: reports
    content_types: 
      - ref
      - vet
      - pop
    form_templates: 
      - common
      - monograph
  - 
    code: conference-papers
    content_types: 
      - ref
      - vet
      - pop
    fields: 
      - 
        name: sourcetitle
        rule: R
    form_templates: 
      - common
      - monograph
  - 
    code: conference-contributions
    content_types: 
      - ref
      - vet
      - pop
    fields: 
      - 
        name: sourcetitle
        rule: R
    form_templates: 
      - common
      - monograph
