---

publication_identifier_codes:
  -
    code: doi
    rule: "10.1214/ECP.v20-4328"
  -
    code: isi-id
    rule: "000358294500016"
  -
    code: pubmed
    rule: "25972573"
  -
    code: scopus-id
    rule: "24924529689"
  -
    code: handle
    rule: "2077/38761"
  -
    code: libris-id
    rule: "16559180"

