---

publication_identifier_codes:
  -
    code: DOI
    rule: "10.1214/ECP.v20-4328"
  -
    code: IDI-ID
    rule: "000358294500016"
  -
    code: Pubmed-ID
    rule: "25972573"
  -
    code: Scopus-ID
    rule: "24924529689"
  -
    code: Handle-ID
    rule: "2077/38761"
  -
    code: Libris-ID
    rule: "16559180"

